### ISSUE TITLE
Don't think this package works anymore...?

### ISSUE THREAD

**Issue by Siyfion** [nate-strauser/meteor-x-editable-bootstrap#35] opened 2015-07-01 14:47 UTC
Firstly when I added the package the Meteor server died and then after being restarted it simply doesn't seem to work, as I keep getting the following error:

```
Uncaught TypeError: Cannot read property 'Constructor' of undefined(anonymous function) @ bootstrap-editable.js:4707
```

**Comment by Siyfion** [comment] 2015-07-01 14:48
@nate-strauser Are you still actively maintaining this project? If not I might look at creating a wrapper myself.

**Comment by nate-strauser** [comment] 2015-07-01 14:53
i'm still maintaining this - i just created a new project and added this and i get no errors

```
$ meteor create x-edit-test
x-edit-test: created.                         

To run your new app:                          
  cd x-edit-test                              
  meteor                                      
$ cd x-edit-test/      
$ meteor add natestrauser:x-editable-bootstrap
                                                                                
Changes to your project's package version selections:
                                              
natestrauser:x-editable-bootstrap  added, version 1.5.2_2

                                              
natestrauser:x-editable-bootstrap: Latest version of X-Editable for Bootstrap
with wysihtml5 rich text editor
:x-edit-test nate$ meteor            
[[[[[ ~/Documents/Projects/x-edit-test ]]]]]  

=> Started proxy.                             
=> Started MongoDB.                           
=> Started your app.                          

=> App running at: http://localhost:3000/
^C
:x-edit-test nate$ meteor --production
[[[[[ ~/Documents/Projects/x-edit-test ]]]]]  

=> Started proxy.                             
=> Started MongoDB.                           
=> Started your app.                          

=> App running at: http://localhost:3000/

```

are you able to replicate this is a new/empty project?

**Comment by Siyfion** [comment] 2015-07-01 15:04
Are these instructions still valid: http://stackoverflow.com/questions/22867690/how-do-i-use-x-editable-on-dynamic-fields-in-a-meteor-template-now-with-blaze/23144211#23144211

**Comment by Siyfion** [comment] 2015-07-01 15:05
All I have is a template:

```html
<template name="quantityEditor">
  <span class="editable" title="Rename this document" data-autotext="never">{{this}}</span>
</template>
```

```javascript
Template.quantityEditor.onRendered(function () {
  var self = this;

  self.autorun(function () {
    // Trigger this whenever data source changes
    Template.currentData();

    // Destroy old editable if it exists
    self.$(".editable").editable("destroy").editable({
      display: function () {

      },
      success: function (response, newValue) {

      }
    });
  });
});
```

**Comment by nate-strauser** [comment] 2015-07-01 15:39
that looks ok to me -since there does not appear to be a problem with the package itself,  i'm going to close this issue

**Closed by nate-strauser** 2015-07-01 15:39 UTC

**Comment by Siyfion** [comment] 2015-07-01 15:45
@nate-strauser What!? I just said, I installed your package, followed your instructions and it throws errors all over the place. How is that closed!?

Here's my package list:

```
accounts-base                       1.2.0  A user account system
accounts-password                   1.1.1  Password support for accounts
alanning:roles                      1.2.13  Role-based authorization
aldeed:collection2                  2.3.3  Automatic validation of insert and update operations on the client and server.
aldeed:simple-schema                1.3.3  A simple schema validation object with reactivity. Used by collection2 and autoform.
chrismbeckett:toastr                2.1.0  Gnome / Growl type non-blocking notifications
edgee:slingshot                     0.7.1  Directly post files to cloud storage services, such as AWS-S3.
fortawesome:fontawesome             4.3.0  Font Awesome (official): 500+ scalable vector icons, customizable via CSS, Retina friendly
gwendall:impersonate                0.2.1  Impersonate users in Meteor
http                                1.1.0  Make HTTP calls to remote servers
ian:accounts-ui-bootstrap-3         1.2.61* Bootstrap-styled accounts-ui with multi-language support.
iron:router                         1.0.9  Routing specifically designed for Meteor
less                                1.0.14  The dynamic stylesheet language
matb33:collection-hooks             0.7.13  Extends Mongo.Collection with before/after hooks for insert/update/remove/find/findOne
meteor-platform                     1.2.2  Include a standard set of Meteor packages in your app
meteorhacks:cluster                 1.6.7* Clustering solution for Meteor with load balancing and service discovery.
meteorhacks:kadira                  2.22.0  Performance Monitoring for Meteor
meteorhacks:kadira-debug            1.3.2* Full Stack Debugging Solution for Meteor
mizzao:bootboxjs                    4.4.0  Programmatic dialog boxes using Twitter's bootstrap modals
momentjs:moment                     2.10.3  Moment.js (official): parse, validate, manipulate, and display dates - official Meteor packaging
msavin:jetsetter                    1.0.17* Visual Get/Set Tool for Sessions
msavin:mongol                       1.0.97* The insanely handy development package for Meteor.
natestrauser:select2                3.5.1  Select2 is a jQuery based replacement for select boxes.
natestrauser:x-editable-bootstrap   1.5.2_2  Latest version of X-Editable for Bootstrap with wysihtml5 rich text editor
nemo64:bootstrap                    3.3.4_2  Highly configurable bootstrap integration.
peerlibrary:async                   0.9.2_1  Async provides straight-forward, powerful functions for working with asynchronous JavaScript
peerlibrary:aws-sdk                 2.1.17_1  SDK for AWS services including Amazon S3, Amazon EC2, DynamoDB, and Amazon SWF
percolate:synced-cron               1.2.1  Allows you to define and run scheduled jobs across multiple servers.
reactive-dict                       1.1.0  Reactive dictionary
reactive-var                        1.0.5  Reactive variable
rubaxa:sortable                     1.2.0  Sortable: reactive minimalist reorderable drag-and-drop lists on modern browsers and touch devices
ryanswapp:spectrum-colorpicker      0.0.1  A meteor wrapper for the spectrum colorpicker
sergeyt:typeahead                   0.11.1_1  Autocomplete package for meteor powered by twitter typeahead.js
siyfion:webfontloader               1.5.18  Web Font Loader gives you added control when using linked fonts via @font-face.
snapsvg:core                        0.4.0  Snap.svg (official): The JavaScript library for modern SVG graphics.
tmeasday:publish-counts             0.4.0  Publish the count of a cursor, in real time
underscore                          1.0.3  Collection of small helpers: _.map, _.each, ...
underscorestring:underscore.string  3.1.1  underscore.string (official): String manipulation extensions for Underscore.js javascript library.
```

**Comment by Siyfion** [comment] 2015-07-01 15:50
This is the line: `defaults: $.fn.popover.Constructor.DEFAULTS,`
and the reason is because `$.fn.popover` is undefined.

**Comment by nate-strauser** [comment] 2015-07-01 15:53
are you including popovers from bootstrap? - check your bootstrap config used by nemo64:bootstrap

i closed the issue because from my testing with a new project it seems that there is not an issue with the package itself

**Comment by Siyfion** [comment] 2015-07-01 15:54
Yep, I am.

**Comment by Siyfion** [comment] 2015-07-02 09:11
@nate-strauser Not sure what more information I can give than that.. :sos:

**Comment by nate-strauser** [comment] 2015-07-02 12:10
sorry @Siyfion i don't know what else to tell you - it appears that this is a problem with your particular app/configuration - you could try a different bootstrap package or maybe try messing with the package order in `.meteor/packages`

if you can supply me with a repo that minimally reproduces this error, i'll take a look - as i mentioned, it appears to work fine in an brand new project so i'm confident there is not an issue with the package itself - also no one else has complained about this problem, which likely means that it is something with your implementation

this package is just a simple wrapper to easily include another library into a meteor app - if you get the x-editable code loaded into your app, then this package is properly working

**Comment by Siyfion** [comment] 2015-07-02 13:27
It's quite likely a compatibilty issue with the x-editable package itself, rather than your wrapper, but it's so broken I don't really know where to start.

**Comment by nate-strauser** [comment] 2015-07-02 13:41
try messing with package order - try removing packages - try to start with a blank app and add things in till it breaks

**Comment by Siyfion** [comment] 2015-07-02 15:06
Ah.. well I've temporarily removed `nemo64:bootstrap` and added `twbs:bootstrap` and it now works... :worried:
